[GLOBAL]
pants_version = "2.15.0rc7"

backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.autoflake",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.python.typecheck.mypy",
]

[anonymous-telemetry]
enabled = true
repo_id = "7b104180-82fa-11ed-937c-00155d25fe7b"

[autoflake]
version = "autoflake"
lockfile = "pants-support/tool-locks/autoflake.lock"

[black]
version = "black"
lockfile = "pants-support/tool-locks/black.lock"

[isort]
version = "isort"
lockfile = "pants-support/tool-locks/isort.lock"

[mypy]
version = "mypy"
config = "pyproject.toml"
lockfile = "pants-support/tool-locks/mypy.lock"

[pex-cli]
version = "v2.1.123"
known_versions = [
    "v2.1.123|linux_arm64|3a2cba02946eb8859393906673bb56ecf6ebee72961bc8f3ca1ae754493733c6|4076395",
    "v2.1.123|linux_x86_64|3a2cba02946eb8859393906673bb56ecf6ebee72961bc8f3ca1ae754493733c6|4076395",
    "v2.1.123|macos_arm64|3a2cba02946eb8859393906673bb56ecf6ebee72961bc8f3ca1ae754493733c6|4076395",
    "v2.1.123|macos_x86_64|3a2cba02946eb8859393906673bb56ecf6ebee72961bc8f3ca1ae754493733c6|4076395",
]

[pytest]
# N.B.: Keep aligned with requirements.txt.
version = "pytest==7.2.1"
lockfile = "pants-support/tool-locks/pytest.lock"

[python]
enable_resolves = true
interpreter_constraints = ["==3.11.*"]

[python.resolves]
python-default = "lock.json"

[python.resolves_to_interpreter_constraints]
# This non-DRY re-declaration of the default IC above is bugged here:
#  https://github.com/pantsbuild/pants/issues/17978
python-default = ["==3.11.*"]

[source]
root_patterns = [
    "/"
]
