[GLOBAL]
pants_version = "2.16.0rc0"

backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.autoflake",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.python.typecheck.mypy",
]

[anonymous-telemetry]
enabled = true
repo_id = "7b104180-82fa-11ed-937c-00155d25fe7b"

[autoflake]
version = "autoflake"
lockfile = "pants-support/tool-locks/autoflake.lock"

[black]
version = "black"
lockfile = "pants-support/tool-locks/black.lock"

[isort]
version = "isort"
lockfile = "pants-support/tool-locks/isort.lock"

[mypy]
version = "mypy"
config = "pyproject.toml"
lockfile = "pants-support/tool-locks/mypy.lock"

[pex-cli]
version = "v2.1.133"
known_versions = [
    "v2.1.133|macos_arm64|2b1e4eaeeebedb939af33cfdade5d260003488f55864e18a13355804586b42b6|4084722",
    "v2.1.133|macos_x86_64|2b1e4eaeeebedb939af33cfdade5d260003488f55864e18a13355804586b42b6|4084722",
    "v2.1.133|linux_x86_64|2b1e4eaeeebedb939af33cfdade5d260003488f55864e18a13355804586b42b6|4084722",
    "v2.1.133|linux_arm64|2b1e4eaeeebedb939af33cfdade5d260003488f55864e18a13355804586b42b6|4084722"
]

[pytest]
# N.B.: Keep aligned with requirements.txt.
version = "pytest==7.3.1"
lockfile = "pants-support/tool-locks/pytest.lock"

[python]
enable_resolves = true
interpreter_constraints = ["==3.11.*"]
pip_version = "23.0.1"

[python.resolves]
python-default = "lock.json"

[source]
root_patterns = [
    "/"
]
