[science]
name = "science"
description = "Ship your interpreted executables using science."

[[science.interpreters]]
id = "cpython"
provider = "PythonBuildStandalone"
release = "20230116"
version = "3.11.1"
lazy = true

[[science.files]]
name = "science.pyz"

[[science.commands]]
exe = "#{cpython:python}"
args = [
    "{science.pyz}",
]
env.remove_re = [
    "SHIV_.*",
]

[science.commands.env.replace]
SHIV_ROOT = "{scie.bindings}/shiv_root"
